wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1634722986
    t:
      1:
      - 1
      4: 3.9.7
      5: 0.12.1
      8:
      - 4
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 8
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: ''
data:
  desc: null
  value: /Users/ryemigie/OneDrive/University Documents/2021/Semester 2/COMP3710/Project/PatternFlow/recognition/s4427545_ISICs/yolov5/utils/isic.yaml
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 2
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value: 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.1
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 512
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
patience:
  desc: null
  value: 100
project:
  desc: null
  value: yolov5/runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: yolov5/runs/train/exp6
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5n
workers:
  desc: null
  value: 8
